# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=60)),
        ),
    ]
