# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20180507_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
